-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 15:24:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdsistsport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdsistsport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsistsport` DEFAULT CHARACTER SET utf8 ;
USE `bdsistsport` ;

-- -----------------------------------------------------
-- Table `bdsistsport`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Talles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Talles` (
  `idTalle` INT NOT NULL AUTO_INCREMENT,
  `unidad` VARCHAR(10) NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idTalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Colores` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Materiales` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `textura` VARCHAR(45) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Prendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Prendas` (
  `idPrendas` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `idColor` INT NOT NULL,
  `idTalle` INT NOT NULL,
  `idMaterial` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(125) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPrendas`),
  CONSTRAINT `fk_Prendas_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdsistsport`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prendas_Talles1`
    FOREIGN KEY (`idTalle`)
    REFERENCES `bdsistsport`.`Talles` (`idTalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prendas_Colores1`
    FOREIGN KEY (`idColor`)
    REFERENCES `bdsistsport`.`Colores` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prendas_Materiales1`
    FOREIGN KEY (`idMaterial`)
    REFERENCES `bdsistsport`.`Materiales` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Empresas` (
  `idEmpresas` INT NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `imagen` VARCHAR(255) NULL,
  `cuil` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEmpresas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Ingresos` (
  `idIbgresos` INT NOT NULL AUTO_INCREMENT,
  `idProveedores` INT NOT NULL,
  `num_comprobante` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idIbgresos`),
  CONSTRAINT `fk_ingresos_empresa`
    FOREIGN KEY (`idProveedores`)
    REFERENCES `bdsistsport`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Estados` (
  `idEstados` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `numeroPedido` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` VARCHAR(10) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  CONSTRAINT `fk_Pedidos_Estados1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `bdsistsport`.`Estados` (`idEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Egresos` (
  `idEgresos` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NULL,
  `num_comprobante` INT NOT NULL,
  `fecha` DATETIME NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`idEgresos`),
  CONSTRAINT `fk_Egresos_Pedidos1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `bdsistsport`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Marcas` (
  `idMarcas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Detalle_Ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Detalle_Ingresos` (
  `idDetalle_Ingresos` INT NOT NULL AUTO_INCREMENT,
  `idIngreso` INT NOT NULL,
  `idPrenda` INT NOT NULL,
  `idMarca` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idDetalle_Ingresos`),
  CONSTRAINT `fk_Detalle_Ingresos_Prendas1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `bdsistsport`.`Prendas` (`idPrendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Ingresos_Ingreso1`
    FOREIGN KEY (`idIngreso`)
    REFERENCES `bdsistsport`.`Ingresos` (`idIbgresos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Ingresos_Marcas1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `bdsistsport`.`Marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Detalle_Egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Detalle_Egresos` (
  `idDetalle_Egresos` INT NOT NULL AUTO_INCREMENT,
  `idEgreso` INT NOT NULL,
  `idPrenda` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idDetalle_Egresos`),
  CONSTRAINT `fk_Detalle_Egreso_Egreso1`
    FOREIGN KEY (`idEgreso`)
    REFERENCES `bdsistsport`.`Egresos` (`idEgresos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Egreso_Prendas1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `bdsistsport`.`Prendas` (`idPrendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Metodo_Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Metodo_Pagos` (
  `idMetdo_Pagos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idMetdo_Pagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Transacciones` (
  `idTransacciones` INT NOT NULL AUTO_INCREMENT,
  `idMetodo` INT NOT NULL,
  `importe` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`idTransacciones`),
  CONSTRAINT `fk_Transaccion_Metodo_Pagos1`
    FOREIGN KEY (`idMetodo`)
    REFERENCES `bdsistsport`.`Metodo_Pagos` (`idMetdo_Pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacciones_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `bdsistsport`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Detalle_Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Detalle_Transacciones` (
  `idDetalle_Transacciones` INT NOT NULL AUTO_INCREMENT,
  `idEgreso` INT NOT NULL,
  `idTransaccion` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Transacciones`),
  CONSTRAINT `fk_Detalle_Transacciones_Egresos1`
    FOREIGN KEY (`idEgreso`)
    REFERENCES `bdsistsport`.`Egresos` (`idEgresos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Transacciones_Transacciones1`
    FOREIGN KEY (`idTransaccion`)
    REFERENCES `bdsistsport`.`Transacciones` (`idTransacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsistsport`.`Detalle_Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsistsport`.`Detalle_Pedidos` (
  `idDetalle_Pedidos` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `dPrendas` INT NOT NULL,
  `idPedidos` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Pedidos`),
  CONSTRAINT `fk_Detalle_Pedidos_Prendas1`
    FOREIGN KEY (`dPrendas`)
    REFERENCES `bdsistsport`.`Prendas` (`idPrendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Pedidos_Pedidos1`
    FOREIGN KEY (`idPedidos`)
    REFERENCES `bdsistsport`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
